version: '3'
services:
   snowcover-gpl:
      restart: always
      build:
         context: .
         dockerfile: Dockerfile
      env_file:
         - .env
      environment: 
         - TZ=Europe/Zurich 
         - C_FORCE_ROOT="true"
      volumes:
         - ~/geodata-test:/data
   # Redis
   redis:
      image: redis
